version: "2.2"

services:
  frontend:
    build: streamlit-frontend
    ports:
      - 8501:8501
    networks:
      - deploy_network
    depends_on:
      - backend

  backend:
    build: fastapi-backend
    ports:
      - 8000:8000
    networks:
      - deploy_network
networks:
  deploy_network:
    driver: bridge